### PR TITLE
Make the service compatible with serverless and edge Function

### PR DESCRIPTION
**Pull request by 1395173231**
The new zlib dependency of the project cannot be used in the Vercel environment. In fact, zlib compression is not necessarily required to obtain Messages through Websocket, which can be removed to obtain compatibility. Add discord reverse generation configuration options to support more network environments
=========================
项目新增的zlib依赖无法在Vercel环境中使用,实际上通过Websocket获取Message并不一定需要zlib压缩, 可以去除以获取兼容性, 增加discord反代配置选项支持更多的网络环境

### CODE REVIEW

**Comment by zcpua** [comment]
ignore .idea

**Comment by zcpua** [comment]
thanks

**Comment by 1395173231** [comment]
Ok, I have committed the version of ignore .idea

> ignore .idea

**Comment by zcpua** [comment]
image

**Comment by 1395173231** [comment]
> image

I have finished the modifications and conducted a simple verification. Please check

**Pull request merged**
